# -*- coding: utf-8 -*-
"""Cancer_Project_Radiogenomics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nn-vNr1l7y6_vgKUNMbq5KAXBGfRu0i1
"""

!pip install SimpleITK==2.3.1 tqdm pandas numpy

"""### Gene Name String Analysis

Let's perform some basic string analysis on the gene names (columns of `rna_scaled`) to check for correctness and consistency.
"""

print("Sample of gene names (columns):")
display(rna_scaled.columns.to_list()[:20])

import re

# Check for gene names containing special characters (e.g., not alphanumeric, underscore, or hyphen)
special_char_genes = [col for col in rna_scaled.columns if not re.match("^[a-zA-Z0-9_-]*$", col)]

print(f"Number of gene names with special characters: {len(special_char_genes)}")
if special_char_genes:
    print("Genes with special characters (first 10):", special_char_genes[:10])
else:
    print("No gene names with special characters found (only alphanumeric, underscore, hyphen).")

# Check for duplicate gene names
duplicate_genes = rna_scaled.columns[rna_scaled.columns.duplicated()].unique()

print(f"Number of duplicate gene names: {len(duplicate_genes)}")
if duplicate_genes:
    print("Duplicate gene names:", duplicate_genes)
else:
    print("No duplicate gene names found.")

# Check min/max/average length of gene names
gene_lengths = [len(col) for col in rna_scaled.columns]

print(f"Min gene name length: {min(gene_lengths)}")
print(f"Max gene name length: {max(gene_lengths)}")
print(f"Average gene name length: {sum(gene_lengths) / len(gene_lengths):.2f}")

!pip install git+https://github.com/AIM-Harvard/pyradiomics.git

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os, pandas as pd, numpy as np
BASE = '/content/drive/MyDrive/Radiogenomics_Dataset'   # change to your path
IMAGES_ROOT = os.path.join(BASE, 'Images and Segmentations', 'NSCLC Radiogenomics')
RNA_FILE = os.path.join(BASE, 'RNA Sequence', 'GSE103584_R01_NSCLC_RNAseq.txt')
CLINICAL_FILE = os.path.join(BASE, 'Clinical Data.csv')
NSCLS_FILE = os.path.join(BASE, 'NSCLC_Radiogenomics.xlsx')

"""**RNA Sequence Preprocessing**"""

# import pandas as pd
# from sklearn.preprocessing import StandardScaler
# from sklearn.feature_selection import VarianceThreshold

# # 1. Read RNA: try tab, fallback to whitespace
# try:
#     rna_df_mat = pd.read_csv(RNA_FILE, sep='\t', index_col=0, engine='python')
# except Exception:
#     rna_df_mat = pd.read_csv(RNA_FILE, sep='\\s+', index_col=0, engine='python')

# # 2. Transpose to have patients as rows
# rna_df = rna_df_mat.T
# rna_df.index = rna_df.index.astype(str)

# # 3. Handle missing values (median imputation)
# rna_df = rna_df.fillna(rna_df.median())

# # 4. Remove constant genes (zero variance)
# selector = VarianceThreshold(threshold=0.0)
# rna_df = pd.DataFrame(selector.fit_transform(rna_df),
#                       index=rna_df.index,
#                       columns=rna_df.columns[selector.get_support()])

# # 5. Standardize (zero mean, unit variance)
# scaler = StandardScaler()
# rna_scaled = pd.DataFrame(scaler.fit_transform(rna_df),
#                           index=rna_df.index,
#                           columns=rna_df.columns)

# print("RNA shape (patients x genes):", rna_df.shape)
# print(rna_df.head())


import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import VarianceThreshold


# 1. Read RNA: try tab, fallback to whitespace
try:
    rna_df_mat = pd.read_csv(RNA_FILE, sep='\t', index_col=0, engine='python')
except Exception:
    rna_df_mat = pd.read_csv(RNA_FILE, sep='\\s+', index_col=0, engine='python')

# 2. Transpose to have patients as rows
rna_df = rna_df_mat.T
rna_df.index = rna_df.index.astype(str)

# 3. Handle missing values
# Fill NaNs with median to preserve patients
rna_df = rna_df.fillna(rna_df.median())


# 4. Remove constant genes (zero variance)
selector = VarianceThreshold(threshold=0.0)
rna_df = pd.DataFrame(selector.fit_transform(rna_df),
                      index=rna_df.index,
                      columns=rna_df.columns[selector.get_support()])

# 5. Optional: Keep only top variable genes (e.g., top 5000)
top_n_genes = 5000  # adjust as needed
gene_variances = rna_df.var(axis=0)
top_genes = gene_variances.sort_values(ascending=False).head(top_n_genes).index
rna_df = rna_df[top_genes]

# 6. Standardize (zero mean, unit variance)
scaler = StandardScaler()
rna_scaled = pd.DataFrame(scaler.fit_transform(rna_df),
                          index=rna_df.index,
                          columns=rna_df.columns)


# 7. Ensure minimum 30 patients
if rna_scaled.shape[0] < 30:
    raise ValueError(f"⚠️ Not enough patients after preprocessing: {rna_scaled.shape[0]} < 30")

# 8. Summary
print("RNA shape after preprocessing (patients x genes):", rna_scaled.shape)
print(rna_scaled.head(20))

"""**Clinical Data Processing**"""

# import pandas as pd

# #  Read clinical CSV
# clinical = pd.read_csv(CLINICAL_FILE)

# clinical.columns = clinical.columns.str.strip()

# #  Keep only the columns you care about
# clinical_cols = ['Case ID', 'Age at Histological Diagnosis', 'Gender', 'Smoking status', 'Histology', 'Survival Status']
# clinical = clinical[clinical_cols]

# # Convert Case ID to string
# clinical['Case ID'] = clinical['Case ID'].astype(str)
# rna_scaled.index = rna_scaled.index.astype(str)  # RNA patient IDs as strings

# # Find patients present in both RNA and clinical
# MATCHED_PIDS = list(set(rna_scaled.index) & set(clinical['Case ID']))
# print("Number of matched patients:", len(MATCHED_PIDS))
# print("Matched patient IDs:", MATCHED_PIDS)

# # Filter RNA
# rna_scaled = rna_scaled.loc[MATCHED_PIDS]

# # Filter clinical
# clinical_filtered = clinical[clinical['Case ID'].isin(MATCHED_PIDS)].set_index('Case ID')

# # Optional: fill missing values
# clinical_filtered.fillna({
#     'Age at Histological Diagnosis': clinical_filtered['Age at Histological Diagnosis'].median(),
#     'Gender': 'Unknown'
# }, inplace=True)

# print("Filtered clinical data shape:", clinical_filtered.shape)
# print(clinical_filtered.head(20))

import pandas as pd

# Read clinical CSV
clinical = pd.read_csv(CLINICAL_FILE)

# Remove any leading/trailing spaces in column names
clinical.columns = clinical.columns.str.strip()

# Keep only relevant columns
clinical_cols = ['Case ID', 'Age at Histological Diagnosis', 'Gender', 'Smoking status', 'Histology', 'Survival Status']
clinical = clinical[clinical_cols]

# Filter for AMC patients
clinical_amc = clinical[clinical['Case ID'].str.startswith('AMC')].set_index('Case ID')

# Optional: fill missing values
clinical_amc.fillna({
    'Age at Histological Diagnosis': clinical_amc['Age at Histological Diagnosis'].median(),
    'Gender': 'Unknown'
}, inplace=True)

print("Number of AMC patients:", clinical_amc.shape[0])
print(clinical_amc.head(20))

"""**Matching Patients**"""

# Build mapping only if necessary: R01-023 -> AMC-023
def r01_to_amc(r01):
    if str(r01).startswith('R01-'):
        return 'AMC-' + str(r01).split('-')[-1].zfill(3)
    return r01

clinical['Mapped_AMC'] = clinical['Case ID'].apply(r01_to_amc)


image_pids = set([d for d in os.listdir(IMAGES_ROOT) if os.path.isdir(os.path.join(IMAGES_ROOT,d))])
rna_pids_amc = set([r01_to_amc(idx) for idx in rna_df.index.tolist()])   # if using numeric mapping
clinical_mapped = set(clinical['Mapped_AMC'].astype(str).tolist())

# Strict intersection
matched = sorted(list(image_pids & clinical_mapped & rna_pids_amc))
print("Matched patients (strict):", len(matched))
print(matched)

!pip install pydicom SimpleITK

"""**Convert DICOM to 3D**"""

import pydicom
import numpy as np
import SimpleITK as sitk

def dicom_series_to_sitk(dicom_dir):
    # list dcm files
    files = [os.path.join(dicom_dir,f) for f in os.listdir(dicom_dir) if f.lower().endswith('.dcm')]
    if not files:
        # sometimes files are in nested subfolders. walk deeper:
        for root,_,fnames in os.walk(dicom_dir):
            for f in fnames:
                if f.lower().endswith('.dcm'):
                    files.append(os.path.join(root,f))
    if not files:
        raise FileNotFoundError(f"No DICOM files found in {dicom_dir}")

    # read headers
    slices = [pydicom.dcmread(f, force=True) for f in files]
    # filter only slices that have InstanceNumber / ImagePositionPatient
    slices = [s for s in slices if hasattr(s,'InstanceNumber') or hasattr(s,'ImagePositionPatient')]
    # try sort by InstanceNumber then fallback to ImagePositionPatient z
    try:
        slices = sorted(slices, key=lambda s: int(s.InstanceNumber))
    except Exception:
        slices = sorted(slices, key=lambda s: float(s.ImagePositionPatient[2]))

    img3d = np.stack([s.pixel_array for s in slices], axis=0)
    # spacing
    px = slices[0].PixelSpacing  # [row spacing, col spacing]
    try:
        slice_thickness = float(slices[0].SliceThickness)
    except Exception:
        # estimate from adjacent slices
        if len(slices) > 1:
            z0 = slices[0].ImagePositionPatient[2]
            z1 = slices[1].ImagePositionPatient[2]
            slice_thickness = abs(z1 - z0)
        else:
            slice_thickness = 1.0

    # Convert to SimpleITK image (note: SITK expects z,y,x order when GetImageFromArray)
    sitk_img = sitk.GetImageFromArray(img3d)  # z,y,x
    sitk_img.SetSpacing((float(px[0]), float(px[1]), float(slice_thickness)))
    return sitk_img

# Usage for a patient:
patient = matched[0]   # e.g., 'AMC-028'
# Some datasets have nested structure: find deepest folder that contains .dcm
patient_dir = os.path.join(IMAGES_ROOT, patient)
# if subfolders e.g., patient/date/series, choose the series folder manually or iterate to find one:
series_folder = None
for root, dirs, files in os.walk(patient_dir):
    if any(f.lower().endswith('.dcm') for f in files):
        series_folder = root
        break

sitk_image = dicom_series_to_sitk(series_folder)
print("sitk image size:", sitk_image.GetSize(), "spacing:", sitk_image.GetSpacing())
# optionally write NIfTI for later reuse
out_nii = f"/content/{patient}.nii.gz"
sitk.WriteImage(sitk_image, out_nii)
print("Saved:", out_nii)

pip install pydicom lxml numpy SimpleITK

"""**Extracting 2D coordinates,**
**Finding Region of Interest,**
**For segmentation**
"""

from lxml import etree
import os

aim_folder = "/content/drive/MyDrive/Radiogenomics_Dataset/AIM Annotations/AIM_files_updated-11-10-2020"
all_xml_files = [os.path.join(aim_folder, f) for f in os.listdir(aim_folder) if f.endswith('.xml')]

# Namespace
ns = {'aim': 'gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM'}

# Store coordinates per patient
all_coords = {}

for aim_path in all_xml_files:
    tree = etree.parse(aim_path)
    root = tree.getroot()

    # Extract patient ID (AMC)
    patient_id_elem = root.find('.//aim:id', namespaces=ns)
    patient_id = patient_id_elem.attrib['value'] if patient_id_elem is not None else os.path.basename(aim_path)

    coords = []
    for roi in root.xpath('//aim:TwoDimensionSpatialCoordinate', namespaces=ns):
        x_elem = roi.find('aim:x', namespaces=ns)
        y_elem = roi.find('aim:y', namespaces=ns)
        if x_elem is not None and y_elem is not None:
            x = float(x_elem.attrib['value'])
            y = float(y_elem.attrib['value'])
            coords.append((x, y))

    all_coords[patient_id] = coords

# Now iterate over AMC patient IDs
image_pids = [d for d in os.listdir(IMAGES_ROOT) if d.startswith("AMC-")]

for pid in image_pids:
    roi_points = all_coords.get(pid, [])
    print(f"Patient {pid}: {len(roi_points)} ROI points, first 5: {roi_points[:5]}")

"""**Slicing Of Image, DICOM converting to 3D array, Preprocessing**




"""

!pip install pydicom

import os
import SimpleITK as sitk
import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# Helper functions
# -----------------------------

def dicom_series_to_sitk(series_folder):
    """Load DICOM series into SITK image."""
    try:
        reader = sitk.ImageSeriesReader()
        dicom_names = reader.GetGDCMSeriesFileNames(series_folder)
        reader.SetFileNames(dicom_names)
        image = reader.Execute()
        return image
    except Exception as e:
        print(f" Failed to load {series_folder}: {e}")
        return None

def resample_image(image, new_spacing=[1,1,1]):
    """Resample to uniform voxel spacing."""
    original_spacing = image.GetSpacing()
    original_size = image.GetSize()
    new_size = [int(round(original_size[i] * (original_spacing[i] / new_spacing[i]))) for i in range(3)]
    resampler = sitk.ResampleImageFilter()
    resampler.SetOutputSpacing(new_spacing)
    resampler.SetSize(new_size)
    resampler.SetInterpolator(sitk.sitkLinear)
    resampler.SetOutputDirection(image.GetDirection())
    resampler.SetOutputOrigin(image.GetOrigin())
    return resampler.Execute(image)

def normalize_intensity(image, min_val=-1000, max_val=400):
    """Clip and scale intensity to 0-1 for DL."""
    arr = sitk.GetArrayFromImage(image)
    arr = np.clip(arr, min_val, max_val)
    arr = (arr - min_val) / (max_val - min_val)
    return sitk.GetImageFromArray(arr)

def crop_or_pad(image, target_size=[128,128,128]):
    """Crop/pad to fixed size (for DL)."""
    arr = sitk.GetArrayFromImage(image)
    z, y, x = arr.shape
    target_z, target_y, target_x = target_size
    pad_z = max(0, target_z - z)
    pad_y = max(0, target_y - y)
    pad_x = max(0, target_x - x)
    arr = np.pad(arr,
                 ((pad_z//2, pad_z - pad_z//2),
                  (pad_y//2, pad_y - pad_y//2),
                  (pad_x//2, pad_x - pad_x//2)),
                 mode='constant', constant_values=0)
    arr = arr[:target_z, :target_y, :target_x]
    return sitk.GetImageFromArray(arr)

def view_image(image, slice_index=None, vmin=-1000, vmax=400):
    """Visualize a middle slice (axial) of the image with proper CT windowing."""
    arr = sitk.GetArrayFromImage(image)  # (Z,Y,X)
    z = arr.shape[0]
    if slice_index is None:
        slice_index = z // 2  # middle slice
    plt.imshow(arr[slice_index,:,:], cmap='gray', vmin=vmin, vmax=vmax)
    plt.title(f"Slice {slice_index}")
    plt.axis('off')
    plt.show()

# -----------------------------
# Main code
# -----------------------------

IMAGES_ROOT = "/content/drive/MyDrive/Radiogenomics_Dataset/Images and Segmentations/NSCLC Radiogenomics/"
OUTPUT_DIR = "/content/drive/MyDrive/Radiogenomics_Dataset/Preprocessed_Images/"
os.makedirs(OUTPUT_DIR, exist_ok=True)

for patient_id in os.listdir(IMAGES_ROOT):
    patient_folder = os.path.join(IMAGES_ROOT, patient_id)
    if not os.path.isdir(patient_folder):
        continue

    # Find the main DICOM series (largest series)
    series_folder = None
    max_slices = 0
    for root, dirs, files in os.walk(patient_folder):
        dicom_files = [f for f in files if f.lower().endswith('.dcm')]
        if len(dicom_files) > max_slices:
            max_slices = len(dicom_files)
            series_folder = root

    if series_folder is None:
        print(f"No DICOM for {patient_id}, skipping.")
        continue

    # Load series
    image = dicom_series_to_sitk(series_folder)
    if image is None or image.GetSize()[2] <= 3:
        print(f"{patient_id} is not a valid 3D series, skipping.")
        continue

    print(f" Loaded {patient_id}, shape: {image.GetSize()}, spacing: {image.GetSpacing()}")

    # --------- Visual inspection ---------
    # View middle slice without cropping/padding or normalization
    view_image(image)

    # --------- Preprocessing for DL ---------
    image_proc = resample_image(image, new_spacing=[1,1,1])
    image_proc = normalize_intensity(image_proc)
    image_proc = crop_or_pad(image_proc, target_size=[128,128,128])

    # Save preprocessed image
    out_path = os.path.join(OUTPUT_DIR, f"{patient_id}_preprocessed.nii.gz")
    sitk.WriteImage(image_proc, out_path)
    print(f" Preprocessed {patient_id} saved to {out_path}")

!pip install torch torchvision torchaudio torchmetrics segmentation-models-pytorch SimpleITK matplotlib

!pip install segmentation-models-pytorch
!pip install torch torchvision
!pip install SimpleITK

"""**U-Net segmentation**"""

import os
import torch
import numpy as np
import matplotlib.pyplot as plt
import SimpleITK as sitk
import segmentation_models_pytorch as smp
from torch.utils.data import Dataset, DataLoader


# ==============================
# Dataset class
# ==============================

class NSCLCDataset(Dataset):

    def __init__(self, image_dir):
        self.image_dir = image_dir

        self.image_files = [
            f for f in os.listdir(image_dir)
            if f.endswith("_preprocessed.nii.gz")
        ]

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):

        img_path = os.path.join(self.image_dir, self.image_files[idx])

        image = sitk.ReadImage(img_path)
        img_array = sitk.GetArrayFromImage(image)

        return img_array, self.image_files[idx]


# ==============================
# Load model
# ==============================

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

model = smp.Unet(
    encoder_name="resnet34",
    encoder_weights="imagenet",
    in_channels=1,
    classes=1,
)

model.to(DEVICE)
model.eval()


# ==============================
# Directories
# ==============================

PREPROC_DIR = "/content/drive/MyDrive/Radiogenomics_Dataset/Preprocessed_Images/"
SEGMENTED_DIR = "/content/drive/MyDrive/Radiogenomics_Dataset/Segmented_Images_Unet/"

os.makedirs(SEGMENTED_DIR, exist_ok=True)


# ==============================
# Data loader
# ==============================

dataset = NSCLCDataset(PREPROC_DIR)

loader = DataLoader(
    dataset,
    batch_size=1,
    shuffle=False
)

print("Total patients:", len(dataset))


# ==============================
# Segmentation loop
# ==============================

for img_arrays, filenames in loader:

    img_arrays = img_arrays[0].numpy()

    preds_array = np.zeros_like(img_arrays)

    patient_id = filenames[0].split("_preprocessed")[0]

    Z,H,W = img_arrays.shape

    print("Processing:", patient_id)


    for z in range(Z):

        img_slice = img_arrays[z,:,:]

        img_tensor = torch.tensor(
            img_slice,
            dtype=torch.float32
        ).unsqueeze(0).unsqueeze(0).to(DEVICE)


        with torch.no_grad():

            pred = model(img_tensor)

            pred = torch.sigmoid(pred)

            pred = (pred > 0.5).float()


        preds_array[z,:,:] = pred.cpu().numpy()[0,0]


    # Save segmentation
    out_mask = sitk.GetImageFromArray(preds_array)

    out_path = os.path.join(
        SEGMENTED_DIR,
        f"{patient_id}_unet_mask.nii.gz"
    )

    sitk.WriteImage(out_mask, out_path)

    print("Saved mask:", out_path)


    # ==============================
    # Tri-planar visualization
    # ==============================

    mid_z = Z//2
    mid_y = H//2
    mid_x = W//2

    fig,axes = plt.subplots(1,3, figsize=(15,5))

    axes[0].imshow(img_arrays[mid_z,:,:], cmap="gray")
    axes[0].imshow(preds_array[mid_z,:,:], cmap="Reds", alpha=0.4)
    axes[0].set_title("Axial")

    axes[1].imshow(img_arrays[:,mid_y,:], cmap="gray")
    axes[1].imshow(preds_array[:,mid_y,:], cmap="Reds", alpha=0.4)
    axes[1].set_title("Coronal")

    axes[2].imshow(img_arrays[:,:,mid_x], cmap="gray")
    axes[2].imshow(preds_array[:,:,mid_x], cmap="Reds", alpha=0.4)
    axes[2].set_title("Sagittal")

    plt.show()

print("Segmentation completed.")

!pip install scikit-image

!pip install --upgrade scikit-image

"""**Radiomics feature exraction**



"""

import os
import SimpleITK as sitk
import numpy as np
import pandas as pd
from scipy.stats import skew
from scipy.spatial.distance import pdist

# -----------------------------
# Directories
# -----------------------------
PREPROC_DIR = "/content/Preprocessed_Images/"   # preprocessed NIfTI images
MASK_DIR = "/content/Segmented_Images_Unet/"    # already generated masks
OUTPUT_CSV = "/content/drive/MyDrive/Radiomic_Features_Full.csv"

# -----------------------------
# Helper Functions
# -----------------------------
def compute_max_diameter(mask):
    """
    Memory-safe approximation of maximum 3D tumor diameter (mm)
    using bounding-box corners.
    """
    arr = sitk.GetArrayFromImage(mask)
    coords = np.argwhere(arr > 0)
    if len(coords) == 0:
        return 0.0

    spacing = np.array(mask.GetSpacing())

    # bounding box corners
    min_c = coords.min(axis=0)
    max_c = coords.max(axis=0)

    # physical distance
    diff = (max_c - min_c) * spacing
    return np.linalg.norm(diff)


def compute_shape_features(mask):
    """Compute basic shape features from mask."""
    arr = sitk.GetArrayFromImage(mask)
    voxel_volume = np.prod(mask.GetSpacing())
    coords = np.argwhere(arr > 0)
    if len(coords) == 0:
        return {'Volume':0, 'BBox_X':0, 'BBox_Y':0, 'BBox_Z':0, 'Max3DDiameter':0}
    volume = np.sum(arr>0) * voxel_volume
    min_c = coords.min(axis=0)
    max_c = coords.max(axis=0)
    bbox = max_c - min_c
    max3d = compute_max_diameter(mask)  # true largest distance
    return {'Volume':volume, 'BBox_X':bbox[2], 'BBox_Y':bbox[1], 'BBox_Z':bbox[0], 'Max3DDiameter':max3d}

def compute_intensity_features(image, mask):
    """Compute intensity statistics for the tumor ROI."""
    arr = sitk.GetArrayFromImage(image)
    mask_arr = sitk.GetArrayFromImage(mask)
    roi = arr[mask_arr>0]
    if len(roi) == 0:
        return {'Mean':0,'Median':0,'Std':0,'Skewness':0}
    return {
        'Mean': np.mean(roi),
        'Median': np.median(roi),
        'Std': np.std(roi),
        'Skewness': skew(roi)
    }

# -----------------------------
# Main Feature Extraction Loop
# -----------------------------
all_features = []

for file in os.listdir(PREPROC_DIR):
    if not file.endswith("_preprocessed.nii.gz"):
        continue

    patient_id = file.replace("_preprocessed.nii.gz","")
    img_path = os.path.join(PREPROC_DIR, file)
    mask_path = os.path.join(MASK_DIR, f"{patient_id}_unet_mask.nii.gz")

    if not os.path.exists(mask_path):
        print(f"No mask for {patient_id}, skipping")
        continue

    image = sitk.ReadImage(img_path)
    mask = sitk.ReadImage(mask_path)

    shape_feats = compute_shape_features(mask)
    intensity_feats = compute_intensity_features(image, mask)

    features = {'PatientID': patient_id}
    features.update(shape_feats)
    features.update(intensity_feats)
    all_features.append(features)
    print(f"Features extracted for {patient_id}")

# -----------------------------
# Save to CSV
# -----------------------------
df = pd.DataFrame(all_features)
df.to_csv(OUTPUT_CSV, index=False)
pd.set_option('display.max_columns', None)
display(df)
print(f"Features saved to {OUTPUT_CSV}")